services:
  imersao_alura_agentes_ia_ambiente:
    build:
      context: configuracoes_ambiente
    container_name: imersao_alura_agentes_ia_ambiente
    volumes:
      - './app:/app'
    working_dir: /app
    depends_on:
      - imersao_alura_agentes_ia_dados
  imersao_alura_agentes_ia_dados:
    image: 'mysql:latest'
    container_name: imersao_alura_agentes_ia_dados
    environment:
      - MYSQL_ROOT_PASSWORD=${SENHA_BANCO}
    ports:
      - '${PORTA_BANCO}:3306'
    env_file:
      - .env

