services:
  imersao_alura_agentes_ia_ambiente:
    build:
      context: configuracoes_ambiente
    container_name: imersao_alura_agentes_ia_ambiente
    volumes:
      - './app:/app'
    working_dir: /app
    depends_on:
      - imersao_alura_agentes_ia_dados
    environment:
      - HOST_BANCO=imersao_alura_agentes_ia_dados
      - USUARIO_BANCO=${USUARIO_BANCO}
      - SENHA_BANCO=${SENHA_BANCO}
      - NOME_BANCO=${NOME_BANCO}
      - FLASK_APP=${FLASK_APP}
      - PYTHONPATH=/app:$PYTHONPATH
      - CHAVE_API_GOOGLE=${CHAVE_API_GOOGLE}
    ports:
      - "5000:5000"
  imersao_alura_agentes_ia_dados:
    image: 'mysql:latest'
    container_name: imersao_alura_agentes_ia_dados
    environment:
      - MYSQL_ROOT_PASSWORD=${SENHA_BANCO}
    ports:
      - '${PORTA_BANCO}:3306'
    env_file:
      - .env

